### ISSUE TITLE
Characteristic warning flooding homebridge logs

### ISSUE THREAD

**Issue by michaelyork** [deanlyoung/homebridge-awair-local#16]
Thanks for this great plugin!

Just recently started getting a bunch of these alerts:

`[4/2/2021, 2:35:13 PM] [homebridge-awair-local] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.`

Looks like it refers to this: https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings#this-plugin-generated-a-warning-from-the-characteristic

**Comment by deanlyoung** [comment]
Hey @michaelyork! Thanks for reporting this. Would you be able to run Homebridge in debug mode and send me the relevant portions of the logs?

**Comment by michaelyork** [comment]
Of course! See below. Happening for multiple fields, including `CurrentRelativeHumidity`, etc.

`[4/2/2021, 2:42:41 PM] [homebridge-awair-local] Error: 
    at PM2_5Density.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at PM2_5Density.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at PM2_5Density.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1298:20)
    at AirQualitySensor.Service.setCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at /usr/lib/node_modules/homebridge-awair-local/index.js:204:7
    at tryCatcher (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-awair-local/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)`

**Comment by deanlyoung** [comment]
Looks like this plugin ran into a similar issue...

https://github.com/ilcato/homebridge-fibaro-hc3/commit/6c218b0bf78a073ce8eca11715246f8b4dd04ed7

Still not sure what the root cause would be, which might be a bug in the Local API. Are there any other logs? You can also enable a more verbose output in the logs from the config.

**Comment by michaelyork** [comment]
Err, this might be the device's fault. For some reason the local API on the Element is down (can't access it directly) even though it's still connected to the network. Will try a reboot and report back.

**Comment by michaelyork** [comment]
Yup, that resolved it. I guess there could be a bit stronger error handling for when the API doesn't respond / the device is offline, but all set here. Sorry to bother!

**Comment by deanlyoung** [comment]
No worries! Glad you got it resolved, but I agree... better error handling.
